"""add real food delivery fields

Revision ID: 0b0d95a3dc48
Revises: 
Create Date: 2026-02-05 19:14:24.854091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b0d95a3dc48'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vendor_canteen')
    op.alter_column('canteens', 'college_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_canteens_id'), table_name='canteens')
    op.drop_index(op.f('ix_colleges_id'), table_name='colleges')
    op.drop_index(op.f('ix_menu_items_id'), table_name='menu_items')
    op.create_foreign_key(None, 'menu_items', 'canteens', ['canteen_id'], ['id'])
    op.drop_index(op.f('ix_order_items_id'), table_name='order_items')
    op.add_column('orders', sa.Column('total_amount', sa.Float(), nullable=True))
    op.create_foreign_key(None, 'orders', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'orders', 'canteens', ['canteen_id'], ['id'])
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_users_id'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'total_amount')
    op.create_index(op.f('ix_order_items_id'), 'order_items', ['id'], unique=False)
    op.drop_constraint(None, 'menu_items', type_='foreignkey')
    op.create_index(op.f('ix_menu_items_id'), 'menu_items', ['id'], unique=False)
    op.create_index(op.f('ix_colleges_id'), 'colleges', ['id'], unique=False)
    op.create_index(op.f('ix_canteens_id'), 'canteens', ['id'], unique=False)
    op.alter_column('canteens', 'college_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_table('vendor_canteen',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('canteen_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['canteen_id'], ['canteens.id'], name=op.f('vendor_canteen_canteen_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('vendor_canteen_user_id_fkey')),
    sa.PrimaryKeyConstraint('user_id', 'canteen_id', name=op.f('vendor_canteen_pkey'))
    )
    # ### end Alembic commands ###
