"""add reject_reason and student_note

Revision ID: ff320d17ae03
Revises: 0b0d95a3dc48
Create Date: 2026-03-15 19:23:36.363808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff320d17ae03'
down_revision: Union[str, Sequence[str], None] = '0b0d95a3dc48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('canteens', 'image_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('canteens', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'open'::text"))
    op.alter_column('menu_items', 'image_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('order_items', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('fk_order_items_menu'), 'order_items', type_='foreignkey')
    op.drop_constraint(op.f('fk_order'), 'order_items', type_='foreignkey')
    op.add_column('orders', sa.Column('reject_reason', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('student_note', sa.String(), nullable=True))
    op.alter_column('orders', 'phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('orders', 'address',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.alter_column('users', 'phone',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.alter_column('orders', 'address',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('orders', 'phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('orders', 'student_note')
    op.drop_column('orders', 'reject_reason')
    op.create_foreign_key(op.f('fk_order'), 'order_items', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_order_items_menu'), 'order_items', 'menu_items', ['menu_item_id'], ['id'], ondelete='CASCADE')
    op.alter_column('order_items', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('menu_items', 'image_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('canteens', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'open'::text"))
    op.alter_column('canteens', 'image_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
